# Generated by Django 4.2.2 on 2023-06-29 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=3)),
                ('fname', models.CharField(max_length=40)),
                ('lname', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=80)),
                ('phone', models.IntegerField(verbose_name=16)),
                ('countrycode', models.IntegerField(verbose_name=4)),
                ('image', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=100)),
                ('created', models.DateField(auto_now_add=True)),
                ('lastvisit', models.CharField(max_length=40)),
            ],
        ),
    ]
