# Generated by Django 4.2.2 on 2023-06-29 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_rename_user_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Members',
        ),
    ]
