# Generated by Django 4.2.2 on 2023-06-29 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_rename_users_members'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Members',
            new_name='Member',
        ),
    ]
