# Generated by Django 4.2.2 on 2023-06-29 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_alter_member_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='fname',
            new_name='fName',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='image',
            new_name='imageUrl',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='lastvisit',
            new_name='lastVisit',
        ),
        migrations.RemoveField(
            model_name='member',
            name='pname',
        ),
        migrations.AlterField(
            model_name='member',
            name='countrycode',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
