# Generated by Django 4.2.2 on 2023-06-29 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_rename_fname_member_fname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='fName',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='lname',
            new_name='lastName',
        ),
    ]
