# Generated by Django 4.2.2 on 2023-06-29 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_rename_fname_member_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='countrycode',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='firstName',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='imageUrl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='lastName',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='token',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
